os: linux
dist: bionic
language: shell
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel
git:
  submodules: false

before_install:
  - openssl aes-256-cbc -K $encrypted_2fc69c4133c3_key -iv $encrypted_2fc69c4133c3_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key

install:
  - git submodule update --init --recursive

before_script:
  - pip3 install --user --upgrade yamllint

script:
  - bash -c 'shopt -s globstar; shellcheck ./**/*.bash ./**/*.sh ./**/setup'
  - bash -c 'find ./ -iname '*.yaml' -or -iname '*.yml' | xargs yamllint'
  - bash ./.check_set-e.bash
